### ISSUE TITLE
Index.data & Settings.ini

### ISSUE THREAD

**Issue by Christian32307** [ThereGoesTokyo0/RSDKv5#1]
The .data file is still attempted to fetch as RSDKv5.data. When this is fixed though, the game cannot find Settings.ini.

**Comment by Christian32307** [comment]
OK, after testing with the fix I talked about:

It still can't find the ini??
that's weird

**Comment by ThereGoesTokyo0** [comment]
This was a test, someone else got it working. I don't know, but the new branch by Joey can build, and you can do it yourself easily. It is not meant to work.
